import { Geist, Geist_Mono } from "next/font/google";
import Link from "next/link";
import "./globals.css";

import { auth } from "@/lib/auth";
import { headers } from "next/headers";
import LogoutButton from "./LogoutButton";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Next App",
  description: "Generated by create next app",
};

type RootLayoutProps = {
  children: React.ReactNode
}

export default async function RootLayout({ children } : RootLayoutProps) {
  const session = await auth.api.getSession({
    headers: await headers(),
  });

  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <nav className="bg-gray-800 text-white p-4 flex gap-4 items-center justify-between">
          <div className="flex gap-4">
            <Link href="/">Karakter</Link>
            <Link href="/todo">To-Do List</Link>
          </div>
          <div className="flex items-center gap-3">
  {session ? (
    <>
      <span>Halo, {session.user.name}</span>
      <LogoutButton />
    </>
  ) : (
    <>
      <Link href="/login" className="hover:text-blue-300">Login</Link>
      <Link href="/register" className="hover:text-blue-300">Register</Link>
    </>
  )}
</div>
        </nav>
        {children}
      </body>
    </html>
  );
}